$(document).ready(function(){
    $("#icon1").click(function(){
        $("#icon1t").toggle();
        $("#img1show").toggle()
    })
    $("#icon3").click(function(){
        $("#icon3t").toggle();
        $("#img3show").toggle();
    })
})